#!/bin/bash

################################################
# Script by <management@codeportal.net>        #
#                                              #
# Script for calculating the size of a folder  #
################################################


if [ -d $1 ]; then
	echo "Size of $1: "$(a=(`du --summarize -h $1`);echo ${a[0]})
else
	echo "Directory not found.."
	exit 1
fi
exit 0
