#!/bin/bash
BASEDIR=$PWD;
SCRIPTFOLDER="medigeek-*";
SCRIPTARCHIVE="kmpd.tar.gz";
SCRIPTFILE="kmpd.py";

cd /tmp;
rm -rf $SCRIPTFOLDER;
wget --no-check-certificate https://github.com/medigeek/kmp-downloader/tarball/master -O $SCRIPTARCHIVE;
tar xzf $SCRIPTARCHIVE;
cd $SCRIPTFOLDER;
python $SCRIPTFILE;

cd ..;
rm -rf $SCRIPTFOLDER;
rm -rf $SCRIPTARCHIVE;
rm -rf $SCRIPTFILE;

cd $BASEDIR;
