#!/bin/bash
set -eu

function is_available {
	command -v $1 >/dev/null 2>&1 || { echo "Required binary '$1' not available." >&2; exit 1; }
}

function remove_older_versions() {
    local file="$1"
    local keep="$2"
    keep=$((keep - 1))

    # Remove all old versions beyond KEEP
    for f in "$file".*; do
        [ -e "$f" ] || continue
        local num="${f##*.}"
        if [[ "$num" =~ ^[0-9]+$ ]] && (( num >= keep )); then
            rm -f "$f"
        fi
    done

    # Shift remaining files down
    for ((i=keep; i>=1; i--)); do
        [ -f "$file.$i" ] && mv "$file.$i" "$file.$((i+1))"
    done

    # Rotate current backup
    if (( keep > 0 )); then
      [ -f "$file" ] && mv "$file" "$file.1"
    fi
}

is_available yq
is_available jq
is_available numfmt
is_available incus
is_available zfs
is_available pv
is_available grep
is_available awk

MINARGNUM=3
MAXARGNUM=4
if [ $# -lt $(($MINARGNUM)) ] || [ $# -gt $MAXARGNUM ]; then
	COMMAND='help'
else
	COMMAND=${1:-help}
	CONTAINER=$2
	TARGET=$3
	KEEPBACKUPCOUNT="${4:-1}"

	if [ $CONTAINER == '-a' ]; then
		if [ ! -d ${TARGET} ]; then
			echo "Error: directory '${TARGET}' does not exist."
			exit 1
		fi
		container_list="$(incus list -c ns | awk '!/NAME/{ if ( $4 == "RUNNING" ) print $2}')"
		for container in $container_list; do
			$0 $COMMAND $container $TARGET/$container.zfs $KEEPBACKUPCOUNT
		done
		exit 0
	fi

	if [[ ! "$CONTAINER" =~ ^[a-zA-Z0-9] ]]; then
		echo "Error: container name needs to start with alphanumeric character."
		exit 1
	fi

	HASH=$(echo $CONTAINER | shasum | cut -b 1-30)
	SNAPSHOT_INCUS="$HASH"
	SNAPSHOT_ZFS="snapshot-$SNAPSHOT_INCUS"
fi

STORAGENAME=$(incus profile device get default root pool)
POOLNAME=$(incus storage show $STORAGENAME | grep zfs.pool_name: | awk '{print $2}')
POOLDRIVER=$(incus storage show $STORAGENAME | grep driver: | awk '{print $2}')

[ "$POOLDRIVER" != 'zfs' ] && echo "Error: default storage pool is of type '$POOLDRIVER', only ZFS is supported." && exit 1

case "$COMMAND" in
    "export")
		if [ -d ${TARGET} ]; then
			echo "Error: file '${TARGET}' is a directory."
			exit 1
		fi
		incus info $CONTAINER >/dev/null
		CONTAINER_STATE=$(incus query /1.0/instances/$CONTAINER | jq .status)
		incus snapshot delete $CONTAINER $SNAPSHOT_INCUS 2>/dev/null || true
		[ $CONTAINER_STATE == '"Running"' ] && incus stop $CONTAINER 2>/dev/null || true
		incus snapshot create --no-expiry $CONTAINER $SNAPSHOT_INCUS
		[ $CONTAINER_STATE == '"Running"' ] && incus start $CONTAINER 2>/dev/null || true
		SIZE=$(zfs send -Pnc $POOLNAME/containers/$CONTAINER@$SNAPSHOT_ZFS | grep size | awk '{print $2}')
		remove_older_versions $TARGET $KEEPBACKUPCOUNT
		zfs send -c $POOLNAME/containers/$CONTAINER@$SNAPSHOT_ZFS | pv -s $SIZE > ${TARGET}
		incus snapshot delete $CONTAINER $SNAPSHOT_INCUS
        ;;
    "import")
		if [ ! -f ${TARGET} ]; then
			echo "Error: file '${TARGET}' does not exist."
			exit 1
		fi
		incus create $CONTAINER --empty >/dev/null
		pv < ${TARGET} | zfs receive -F $POOLNAME/containers/$CONTAINER
		zfs destroy $POOLNAME/containers/$CONTAINER@%
        ;;
	*)
		echo
		echo "Wrong parameters! Usage: incus-backup-zfs [export|import] [CONTAINER|-a] FILENAME [KEEP_BACKUP_COUNT]"
		echo "                                                          (-a parameter exports all running containers)"
		echo "This script only works for containers on ZFS storage pools and exports to a native ZFS data file."
		;;
esac
