#!/bin/bash
set -e

function do_import {
	ARGNUM=2
	if [ $# -lt $ARGNUM ] || [ $# -gt $ARGNUM ]; then
	  echo 1>&2 "$0: {imagePath} {containerName}"
	  exit 2
	fi

	IMPORTPATH=$1
	CONTAINER=$2

	echo "-- importing template $IMPORTPATH as container $CONTAINER"

	echo "   importing image file"
	lxc image delete "$CONTAINER-import" 2>/dev/null || true
	lxc image import $IMPORTPATH --alias="$CONTAINER-import" >/dev/null 2>&1

	echo "   creating container"
	lxc init "$CONTAINER-import" $CONTAINER >/dev/null || true

	echo "   cleaning up"
	lxc image delete "$CONTAINER-import" 2> /dev/null

	echo "   done."

}

function do_export {
	ARGNUM=2
	if [ $# -lt $ARGNUM ] || [ $# -gt $ARGNUM ]; then
	  echo 1>&2 "$0: {containerName} {exportPath without .tar.gz}"
	  exit 2
	fi

	if lxc info $1 2>/dev/null | egrep -iqc "status: running"; then
	  ISRUNNING=true
	else
	  ISRUNNING=false
	fi

	CONTAINER=$1
	EXPORTPATH=$2
	TEMPLATE=$(date +%s | sha256sum | base64 | head -c32 ; echo)

	echo "-- exporting container $1 to $2.tar.gz"

	if [ "$ISRUNNING" = true ] ; then
	  echo "   stopping container"
	  lxc stop $CONTAINER 2>/dev/null
	fi

	echo "   creating snapshot"
	lxc delete $CONTAINER/$TEMPLATE 2>/dev/null || true
	lxc snapshot $CONTAINER $TEMPLATE >/dev/null

	if [ "$ISRUNNING" = true ] ; then
	  echo "   starting container"
	  lxc start $CONTAINER
	fi

	echo "   creating image"
	lxc publish $CONTAINER/$TEMPLATE --alias $TEMPLATE >/dev/null

	echo "   exporting image"
	lxc image export $TEMPLATE $EXPORTPATH >/dev/null

	echo "   cleaning up"
	lxc delete $CONTAINER/$TEMPLATE
	lxc image delete $TEMPLATE 2>/dev/null

	echo "   done."
}

case $1 in
        "export")
                do_export $2 $3
                ;;
        "import")
                do_import $2 $3
                ;;
        *)
                echo "Wrong Parameters! Usage: [ export | import | help ]"
                ;;
esac
