#!/bin/bash
set -eu

echo "pushing local file $1 to all containers, path $2"

container_list="$(lxc list -c ns | awk '!/NAME/{ if ( $4 == "RUNNING" ) print $2}')"
for container in $container_list; do
	echo "processing container $container.."
		lxc file push "$1" $container/"$2" || true
done
echo "done."