#!/usr/bin/env bash

_apt="/usr/bin/apt"
_lxc="/usr/bin/lxc"
_awk="/usr/bin/awk"


for i in "$@"
do
case $i in
    -d=*|--dummy=*)
    DUMMY="${i#*=}"
    shift
    ;;
    -y)
    YES=-y
    shift
    ;;
    -s)
    HOST=true
    shift
    ;;
    *)
	echo LXD container upgrade script.
	echo -y : always pass yes to upgrade command
	echo -s : self / update host system
	exit 0
    ;;
esac
done

if [ "$HOST" = true ] ; then
 echo ""
 echo "Upgrading host system..."
 apt -qq update
 apt -qq $YES full-upgrade
 apt -qq $YES autoremove
fi

# Get containers list
clist="$(${_lxc} list -c ns | ${_awk} '!/NAME/{ if ( $4 == "RUNNING" ) print $2}')"

for c in $clist
do
 echo ""
 echo "Upgrading container \"$c\"..."
 ${_lxc} exec $c ${_apt} -- -qq update
 ${_lxc} exec $c ${_apt} -- -qq $YES full-upgrade
 ${_lxc} exec $c ${_apt} -- -qq $YES autoremove
done 
