#!/usr/bin/env bash

command -v incus >/dev/null 2>&1 && BINARY=incus ||
        {
                command -v lxd >/dev/null 2>&1 && BINARY=lxc ||
                        {
                                echo "did not find neither incus nor lxd binary in path." >&2;
                                exit 1;
                        }
        }

# Get containers list
clist="$($BINARY list -c ns | awk '!/NAME/{ if ( $4 == "RUNNING" ) print $2}')"

for i in "$@"
do
case $i in
    -e=*|--exclude=*)
    EXCLUDE_LIST="${i#*=}"
    shift
    ;;
    -h|--help)
        echo -e= / --exclude= : exclude comma-separated container names
        exit 0
    ;;
esac
done

for c in $clist
do
 echo ""
 echo "$c"
 echo "---------------------------------------------------------"
 if [[ $EXCLUDE_LIST =~ (^|,)"$c"(,|$) ]]
  then
   echo "EXCLUDED"
   continue
  else
   $BINARY exec $c -- "$@"
 fi
done
