#!/bin/bash

COMMAND=$1
EXTERNAL_PORT=$2
CONTAINER_NAME=$3
CONTAINER_PORT=$4

IFACE=$(ip -o route show to default | awk '{print $5}' | head -n1)
IPV4=$(dig +short a    $CONTAINER_NAME)
IPV6=[$(dig +short aaaa $CONTAINER_NAME)]

iptables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE
iptables -t nat -A POSTROUTING -o lxcbr0 -j MASQUERADE

ip6tables -t nat -A POSTROUTING -o $IFACE -j MASQUERADE
ip6tables -t nat -A POSTROUTING -o lxcbr0 -j MASQUERADE

case "$COMMAND" in
	add)
		iptables -A PREROUTING -t nat -i $IFACE -p tcp --dport $EXTERNAL_PORT -j DNAT --to $IPV4:$CONTAINER_PORT
		ip6tables -A PREROUTING -t nat -i $IFACE -p tcp --dport $EXTERNAL_PORT -j DNAT --to $IPV6:$CONTAINER_PORT
		;;
        del)
		iptables -D PREROUTING -t nat -i $IFACE -p tcp --dport $EXTERNAL_PORT -j DNAT --to $IPV4:$CONTAINER_PORT
		ip6tables -D PREROUTING -t nat -i $IFACE -p tcp --dport $EXTERNAL_PORT -j DNAT --to $IPV6:$CONTAINER_PORT
		;;
	delall)
		for i in $( iptables -t nat --line-numbers -L PREROUTING | grep ^[0-9] | awk '{ print $1 }' | tac ); do 
			iptables -t nat -D PREROUTING $i;
		done
		for i in $( ip6tables -t nat --line-numbers -L PREROUTING | grep ^[0-9] | awk '{ print $1 }' | tac ); do 
			ip6tables -t nat -D PREROUTING $i;
		done
		;;
	list)
		iptables -t nat --line-numbers -L PREROUTING
		ip6tables -t nat --line-numbers -L PREROUTING
		;;
	*)
		echo "Usage: add/del SOURCEPORT DESTCONTAINER DESTPORT"
esac
