#!/usr/bin/env bash

_apt="/usr/bin/apt"
_lxc="/usr/bin/lxc"
_awk="/usr/bin/awk"


for i in "$@"
do
case $i in
    -e=*|--exclude=*)
    EXCLUDE_LIST="${i#*=}"
    shift
    ;;
    -y)
    YES=-y
    shift
    ;;
    -s)
    HOST=true
    shift
    ;;
    *)
	echo LXD container upgrade script.
	echo -y     : always pass yes to upgrade command
	echo -e=### : exclude comma-separated container names
	echo -s     : self / update host system
	exit 0
    ;;
esac
done

if [ "$HOST" = true ] ; then
 echo ""
 echo "Upgrading host system..."
 apt -qq update &>/dev/null
 apt -qq $YES full-upgrade
 apt -qq $YES autoremove
fi

echo
echo
echo fetching package data..
lxd-exec-all -e=$EXCLUDE_LIST apt -qq $YES update &>/dev/null

echo
echo
echo upgrading containers..
lxd-exec-all -e=$EXCLUDE_LIST apt -qq $YES full-upgrade

echo
echo
echo cleaning containers..
lxd-exec-all -e=$EXCLUDE_LIST apt -qq $YES autoremove
