#!/bin/bash
set -e

if [ -z "$1" ]; then STORAGE=default; else STORAGE="$1"; fi

btrfs filesystem show $STORAGE >/dev/null

LOOPFILE_PATH=$(btrfs filesystem show $STORAGE | awk 'FNR == 3 {print $8}')
BTRFS_UUID=$(btrfs filesystem show $STORAGE | awk 'FNR == 1 {print $4}')
TEMP_MOUNT_PATH=/tmp/btrfs_$BTRFS_UUID

mkdir $TEMP_MOUNT_PATH
mount $LOOPFILE_PATH $TEMP_MOUNT_PATH

IMAGEPATH=$TEMP_MOUNT_PATH
btrfs-size $IMAGEPATH

umount $TEMP_MOUNT_PATH
rmdir $TEMP_MOUNT_PATH
