#!/bin/bash
set -e

ARG_SELF=$0
ARG_COMMAND=$1
ARG_FILESYSTEM=$2

if [ -z "$ARG_FILESYSTEM" ]; then STORAGE=default; else STORAGE="$2"; fi

btrfs filesystem show $STORAGE >/dev/null

LOOPFILE_PATH=$(btrfs filesystem show $STORAGE | awk 'FNR == 3 {print $8}')
IMAGEFILE_PATH=$(losetup | grep $LOOPFILE_PATH | awk 'FNR == 1 {print $6}')
BTRFS_UUID=$(btrfs filesystem show $STORAGE | awk 'FNR == 1 {print $4}')
TEMP_MOUNT_PATH=/tmp/btrfs_$BTRFS_UUID

case "$ARG_COMMAND" in
	mount)
		mkdir $TEMP_MOUNT_PATH
		mount $LOOPFILE_PATH $TEMP_MOUNT_PATH
		echo "Mounted LXD storage $STORAGE on $TEMP_MOUNT_PATH"
	;;
	unmount)
		umount $TEMP_MOUNT_PATH
		rmdir $TEMP_MOUNT_PATH
		echo "Unmounted LXD storage $STORAGE from $TEMP_MOUNT_PATH"
	;;
	list)
		$ARG_SELF mount $ARG_FILESYSTEM
		btrfs subvolume list -t --sort=path $TEMP_MOUNT_PATH
		$ARG_SELF unmount $ARG_FILESYSTEM
		if [ -n "$IMAGEFILE_PATH" ]; then filesize $IMAGEFILE_PATH; fi
		btrfs filesystem show $ARG_FILESYSTEM
	;;
	fstrim)
		$ARG_SELF mount $ARG_FILESYSTEM
		fstrim -v $TEMP_MOUNT_PATH
		$ARG_SELF unmount $ARG_FILESYSTEM
		if [ -n "$IMAGEFILE_PATH" ]; then fstrim -v $(dirname $IMAGEFILE_PATH); fi
	;;
	*)
		echo "Commands: <mount | unmount | list | fstrim> [btrfs_pool_name]"
esac
