#!/bin/bash
set -e

ARG_SELF=$0
ARG_COMMAND=$1
ARG_FILESYSTEM=$2

if [ -z "$ARG_FILESYSTEM" ]; then STORAGE=default; else STORAGE="$2"; fi

btrfs filesystem show $STORAGE >/dev/null

LOOPFILE_PATH=$(btrfs filesystem show $STORAGE | awk 'FNR == 3 {print $8}')
BTRFS_UUID=$(btrfs filesystem show $STORAGE | awk 'FNR == 1 {print $4}')
TEMP_MOUNT_PATH=/tmp/btrfs_$BTRFS_UUID

case "$ARG_COMMAND" in
	mount)
		mkdir $TEMP_MOUNT_PATH
		mount $LOOPFILE_PATH $TEMP_MOUNT_PATH
	;;
	unmount)
		umount $TEMP_MOUNT_PATH
		rmdir $TEMP_MOUNT_PATH
	;;
	size)
		$ARG_SELF mount $ARG_FILESYSTEM
		btrfs-size $TEMP_MOUNT_PATH
		$ARG_SELF unmount $ARG_FILESYSTEM
	;;
	fstrim)
		$ARG_SELF mount $ARG_FILESYSTEM
		fstrim -v $TEMP_MOUNT_PATH
		$ARG_SELF unmount $ARG_FILESYSTEM
	;;
	*)
		echo "Commands: <mount | unmount | size | fstrim> [btrfs_pool_name]"
esac
