#!/bin/bash

ARGNUM=2

if [ $# -lt $ARGNUM ] || [ $# -gt $ARGNUM ]; then
  echo 1>&2 "$0: {containerName} {exportPath without .tar.gz}"
  exit 2
fi

if lxc info $1 | egrep -iqc "status: running"; then
  ISRUNNING=true
else
  ISRUNNING=false
fi

CONTAINER=$1
EXPORTPATH=$2
TEMPLATE=$(date +%s | sha256sum | base64 | head -c32 ; echo)

echo "-- publishing container $1"

if [ "$ISRUNNING" = true ] ; then
  echo "   stopping container"
  lxc stop $CONTAINER 2>/dev/null
fi

echo "   creating snapshot"
lxc snapshot $CONTAINER $TEMPLATE >/dev/null

if [ "$ISRUNNING" = true ] ; then
  echo "   starting container"
  lxc start $CONTAINER
fi

echo "   creating image"
lxc publish $CONTAINER/$TEMPLATE --alias $TEMPLATE >/dev/null

echo "   exporting image"
lxc image export $TEMPLATE $EXPORTPATH >/dev/null

echo "   cleaning up"
lxc delete $CONTAINER/$TEMPLATE
lxc image delete $TEMPLATE 2>/dev/null

echo "   done."
