#!/usr/bin/env bash

# Get containers list
clist="$(lxc list -c ns | awk '!/NAME/{ if ( $4 == "RUNNING" ) print $2}')"

for i in "$@"
do
case $i in
    -e=*|--exclude=*)
    EXCLUDE_LIST="${i#*=}"
    shift
    ;;
    -h|--help)
        echo -e= / --exclude= : exclude comma-separated container names
        exit 0
    ;;
esac
done

for c in $clist
do
 echo ""
 echo "$c"
 echo "---------------------------------------------------------"
 if [[ $EXCLUDE_LIST =~ (^|,)"$c"(,|$) ]]
  then
   echo "EXCLUDED"
   continue
  else
   lxc exec $c -- "$@"
 fi
done
