#!/bin/bash

ARGNUM=2

if [ $# -lt $ARGNUM ]; then
  echo 1>&2 "$0: not enough arguments"
  exit 2
elif [ $# -gt $ARGNUM ]; then
  echo 1>&2 "$0: too many arguments"
  exit 2
fi

if lxc info $1 | egrep -iqc "status: running"; then
  AUTORESTART=true
else
  AUTORESTART=false
fi

CONTAINER=$1
EXPORTPATH=$2
TEMPLATE=$(date +%s | sha256sum | base64 | head -c32 ; echo)

echo "-- publishing container $1"
echo "  (1/5) stopping container"
lxc stop $CONTAINER 2>/dev/null
echo "  (2/5) creating image"
lxc publish $CONTAINER --alias $TEMPLATE >/dev/null
echo "  (3/5) initialising container"
if [ "$AUTORESTART" = true ] ; then
  lxc start $CONTAINER
fi
echo "  (4/5) exporting image"
lxc image export $TEMPLATE $EXPORTPATH >/dev/null
echo "  (5/5) removing local image"
lxc image delete $TEMPLATE 2>/dev/null

echo "  done."
