#!/bin/bash

ARGNUM=2

if [ $# -lt $ARGNUM ]; then
  echo 1>&2 "$0: not enough arguments"
  exit 2
elif [ $# -gt $ARGNUM ]; then
  echo 1>&2 "$0: too many arguments"
  exit 2
fi

lxc image delete $2 2>/dev/null
lxc stop $1
lxc publish $1 --alias $2
lxc start $1
