#!/usr/bin/env php

<?php

function api($apiKey, String $endpoint, $postData = [])
{
    $curl = curl_init();

    curl_setopt_array($curl, array(
        CURLOPT_URL => 'https://api.uptimerobot.com/v2/' . $endpoint,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'POST',
        CURLOPT_POSTFIELDS => 'api_key=' . $apiKey . '&format=json&' . http_build_query($postData),
        CURLOPT_HTTPHEADER => array(
            'cache-control: no-cache',
            'content-type: application/x-www-form-urlencoded'
        ),
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    if ($err) {
        echo 'cURL Error #:' . $err;
    } else {
        return json_decode($response);
    }
    return null;
}

$options = getopt(null, ['pause', 'resume', 'key:']);
$statusPause = array_key_exists('pause', $options);
$statusResume = array_key_exists('resume', $options);

$apiKey = $options['key'];

if ($statusPause xor $statusResume) {
    foreach (api($apiKey, 'getMonitors')->monitors as $monitor) {
        echo $monitor->friendly_name . ' / ' . $monitor->id . "\n";
        api($apiKey, 'editMonitor', ['id' => $monitor->id, 'status' => $statusPause ? 0 : 1]);
    }
} else {
    die("Wrong Parameters! --pause / --resume / --key\n");
}