#!/usr/bin/env php
<?php

function api($apiKey, String $endpoint, $postData = [])
{
    $curl = curl_init();

    curl_setopt_array($curl, array(
        CURLOPT_URL => 'https://api.uptimerobot.com/v2/' . $endpoint,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => '',
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 30,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => 'POST',
        CURLOPT_POSTFIELDS => 'api_key=' . $apiKey . '&format=json&' . http_build_query($postData),
        CURLOPT_HTTPHEADER => array(
            'cache-control: no-cache',
            'content-type: application/x-www-form-urlencoded'
        ),
    ));

    $response = curl_exec($curl);
    $err = curl_error($curl);

    curl_close($curl);

    if ($err) {
        echo 'cURL Error #:' . $err;
    } else {
        return json_decode($response);
    }
    return null;
}

function getMonitorDescription($monitor){
    return $monitor->friendly_name . ' / ' . $monitor->id;
}

$options = getopt(null, ['pause', 'resume', 'key:', 'monitor:']);
$statusPause = array_key_exists('pause', $options);
$statusResume = array_key_exists('resume', $options);

$apiKey = isset($options['key']) ? $options['key'] : null;
$monitorId = isset($options['monitor']) ? $options['monitor'] : null;

function cleanMonitorName($name){
	return strtolower(str_replace('-', ' ', $name));
}

if (!empty($apiKey)) {
    foreach (api($apiKey, 'getMonitors')->monitors as $monitor) {
        if ($statusPause xor $statusResume) {
	    if ( empty($monitorId) || $monitor->id == $monitorId || strpos(cleanMonitorName($monitor->friendly_name),cleanMonitorName($monitorId))!==false ){
                api($apiKey, 'editMonitor', ['id' => $monitor->id, 'status' => $statusPause ? 0 : 1]);
                $stateString = $statusPause ? 'Paused' : 'Resumed';
                echo $stateString .' monitor: ' . getMonitorDescription($monitor) ."\n";
            }
        } else {
            echo getMonitorDescription($monitor) . "\n";
        }
    }
} else {
echo <<<EOL
    Description: Uptimerobot monitor status script. List, pause and resume all or specific uptimerobot monitors.
    Parameters:
               --key=      API key of your uptimerobot account
               --pause     Pause matching monitors
               --resume    Resume matching monitors
               --monitor=  ID or name of the selected monitor. If not provided, all monitors are changed

EOL;
}
