#!/bin/bash

# SETTINGS ##############
MAX_QUEUE_SIZE=0
MAIL_TO="root"
HOSTNAME=$(/bin/hostname)
# END SETTINGS ##########

CURRENT_QUEUE_SIZE=$(/usr/sbin/exim -bpc);

if [ "$CURRENT_QUEUE_SIZE" -g "$MAX_QUEUE_SIZE" ]; then
	mail -s "$HOSTNAME - WARNING: Too many messages in exim mail queue ($CURRENT_QUEUE_SIZE/$MAX_QUEUE_SIZE)" "$MAIL_TO" <<< "This Message was generated by your Server Monitoring Tool."
fi
