#!/bin/bash

# SETTINGS ##############
BACKUP_DIR="/mnt/storage"
MAIL_TO="root"
HOSTNAME=$(/bin/hostname)
# END SETTINGS ##########

if [ -d "$BACKUP_DIR" ]; then
	mail -s "$HOSTNAME - WARNING: External Storage-Folder still existing!" "$MAIL_TO" <<< "This Message was generated by your Server Monitoring Tool."
fi
